pipeline{
 agent any
  stages{
    stage('Git Clone') {
      steps {
          checkout scm
      }
    }
  
    stage('Build package') {
      steps {
	  sh 'cd /var/lib/jenkins/workspace/backendPipeline/webapp/recipie_management_system/'
	  sh 'pwd'
	  dir('webapp/recipie_management_system/'){
            sh 'mvn clean install'
          } 
      }
    }
    stage('Build docker image') {
      steps {
	  dir('webapp/recipie_management_system/'){
	  sh '''
          env && docker build -t ${BACKEND_IMAGE_NAME}:${GIT_COMMIT} .
          '''}
      }
    }
	stage('Push image') {
      steps {
          sh '''
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
          docker push ${BACKEND_IMAGE_NAME}:${GIT_COMMIT}
          '''
      }
    }
  }
}
